version: '3.7'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - ./docker-data/db:/bitnami/postgresql
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    volumes:
      - ./docker-data/redis:/bitnami/redis/data
  keycloak:
    extends:
      file: docker-compose.base.yml
      service: keycloak
