version: '3.9'

services:
  db:
    image: bitnami/postgresql:15.3.0
    restart: always
    hostname: postgres
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
    volumes:
      - ./db-config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3
  redis:
    image: bitnami/redis:7.0.11
    restart: always
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_PASSWORD=password123
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
  keycloak:
    image: bitnami/keycloak:21.1.1
    restart: always
    hostname: keycloak
    healthcheck:
      # Keycloak takes time to connect to the database and set itself up
      test: ['CMD-SHELL', 'exit 0']
      start_period: 80s
      interval: 80s
      timeout: 3s
      retries: 2
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_CREATE_ADMIN_USER: ${KEYCLOAK_CREATE_ADMIN_USER}
      KEYCLOAK_ENABLE_STATISTICS: ${KEYCLOAK_ENABLE_STATISTICS}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: ${KEYCLOAK_DATABASE_PORT}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: ${KEYCLOAK_DATABASE_SCHEMA}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME}
    volumes:
      - ./keycloak/themes:/opt/bitnami/keycloak/themes/mynewtheme
