version: '3.7'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  keycloak:
    extends:
      file: docker-compose.base.yml
      service: keycloak
