version: '3.9'

services:
  db-test:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - ${DB_PORT}:5432
  redis-test:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - ${REDIS_PORT}:6379
  keycloak-test:
    extends:
      file: docker-compose.base.yml
      service: keycloak
    ports:
      - ${KEYCLOAK_HOST_PORT}:8080
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      keycloak-test:
        condition: service_healthy
    command: >
      sh -c " \
        env && \
        npm run migrate:init && \
        echo '========002=========' && \
        npx prisma db seed && \
        echo '========003=========' && \
        npm run config-keycloak && \
        echo '========004=========' && \
        npx prisma generate && \
        echo '========005=========' && \
        npm run build && \
        echo '========006=========' && \
        npx playwright test"
