version: '3.9'

services:
  db-test:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - ${DB_PORT}:5432
  redis-test:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - ${REDIS_PORT}:6379
  keycloak-test:
    extends:
      file: docker-compose.base.yml
      service: keycloak
    depends_on:
      db-test:
        condition: service_healthy
        restart: true
    ports:
      - ${KEYCLOAK_HOST_PORT}:8080
